#!/bin/bash

while true
do

# Logo

curl -s https://raw.githubusercontent.com/obajay/nodes-Guides/main/logo_1 | bash

# Menu

PS3='Select an action: '
options=(
"Unpacking the Mainnet archive"
"Check node logs"
"Check node sync"
"Exit"
"Restart node"
"Replace chain-0"
"Replace chain-1"
"Replace chain-56"
"Replace chain-137"
"Replace chain-250"
"Replace chain-42161"
"Replace chain-43114")
select opt in "${options[@]}"
do
case $opt in

"Unpacking the Mainnet archive")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile

echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
#UPDATE APT
sudo apt install lz4

echo -e "              \e[1m\e[32m3. Downloading and unpacking the archive--> \e[0m" && sleep 1
#Lets-GO
cd $HOME
docker stop $EYWANAME
rm -rf /app/.data/leveldb
curl -o - -L http://eywam.snapshot.stavr.tech:1000/eywa/leveldb-eywa.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/ --strip-components 2
mv /app/.data/leveldb/STAVR2 /app/.data/leveldb/$EYWANAME

# start service
docker restart $EYWANAME

echo '=============== SETUP FINISHED ==================='
echo -e 'Congratulations:        \e[1m\e[32mSuccessful unpacking of the archive\e[0m'
echo -e 'To check logs:        \e[1m\e[33mdocker logs -f $EYWANAME --follow --tail=50\e[0m'

break
;;
"Check node logs")
docker logs -f $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Replace chain-0")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-0
curl -o - -L http://eywamchain-0.stavr.tech:1001/chain-0/chain-0.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')



break
;;
"Replace chain-1")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-1
curl -o - -L http://eywamchain-1.stavr.tech:1002/chain-1/chain-1.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Replace chain-56")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-56
curl -o - -L http://eywamchain-56.stavr.tech:1003/chain-56/chain-56.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Replace chain-137")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-137
curl -o - -L http://eywamchain-137.stavr.tech:1004/chain-137/chain-137.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')


break
;;
"Replace chain-250")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-250
curl -o - -L http://eywamchain-250.stavr.tech:1005/chain-250/chain-250.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')


break
;;
"Replace chain-42161")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-42161
curl -o - -L http://eywamchain-42161.stavr.tech:1006/chain-42161/chain-42161.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')


break
;;
"Replace chain-43114")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-43114
curl -o - -L http://eywamchain-43114.stavr.tech:1007/chain-43114/chain-43114.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Restart node")
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')


break
;;
"Check node sync")
curl -s 127.0.0.1:8081/v1/sync_state|jq -r '("NODE SYNC STATE: "+.result.state),((["CHAIN","SYNCED","DIFFS","sysDIFFS"] | (., map(length*"-"))),(.result.details|keys[] as $k |["\($k)", "\(.[$k].synced)", "\(.[$k].diffs.processedHeight)", "\(.[$k].diffs.sysProcessedHeight)"])|@tsv)'

break
;;
"Exit")
exit
esac
done
done
