#!/bin/bash

while true
do

# Logo

curl -s https://raw.githubusercontent.com/obajay/nodes-Guides/main/logo_1 | bash

# Menu

PS3='Select an action: '
options=(
"Unpacking the Testnet archive"
"Check node logs"
"Check node sync"
"Exit"
"Restart node"
"Replace chain-0"
"Replace chain-5"
"Replace chain-97"
"Replace chain-4002"
"Replace chain-43113"
"Replace chain-80001"
"Replace chain-421613")
select opt in "${options[@]}"
do
case $opt in

"Unpacking the Testnet archive")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile

echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
#UPDATE APT
sudo apt install lz4

echo -e "              \e[1m\e[32m3. Downloading and unpacking the archive--> \e[0m" && sleep 1
#Lets-GO
cd $HOME
docker stop $EYWANAME
rm -rf /app/.data/leveldb
curl -o - -L http://eywa.snapshot.stavr.tech:1000/eywa/leveldb-eywa.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/ --strip-components 2
mv /app/.data/leveldb/STAVR /app/.data/leveldb/$EYWANAME

# start service
docker restart $EYWANAME

echo '=============== SETUP FINISHED ==================='
echo -e 'Congratulations:        \e[1m\e[32mSuccessful unpacking of the archive\e[0m'
echo -e 'To check logs:        \e[1m\e[33mdocker logs -f $EYWANAME --follow --tail=50\e[0m'

break
;;
"Check node logs")
docker logs -f $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Replace chain-0")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-0
curl -o - -L http://eywatchain-0.stavr.tech:1001/chain-0/chain-0.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')



break
;;
"Replace chain-5")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-5
curl -o - -L http://eywatchain-5.stavr.tech:1007/chain-5/chain-5.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Replace chain-97")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-97
curl -o - -L http://eywatchain-97.stavr.tech:1006/chain-97/chain-97.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Replace chain-4002")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-4002
curl -o - -L http://eywatchain-4002.stavr.tech:1005/chain-4002/chain-4002.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')


break
;;
"Replace chain-43113")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-43113
curl -o - -L http://eywatchain-43113.stavr.tech:1004/chain-43113/chain-43113.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')


break
;;
"Replace chain-80001")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-80001
curl -o - -L http://eywatchain-80001.stavr.tech:1003/chain-80001/chain-80001.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')


break
;;
"Replace chain-421613")
echo "*********************"
echo -e "\e[1m\e[35m		Lets's begin\e[0m"
echo "*********************"
echo -e "\e[1m\e[32m	Enter your Validator_Name:\e[0m"
echo "_|-_|-_|-_|-_|-_|-_|"
read EYWANAME
echo "_|-_|-_|-_|-_|-_|-_|"
echo export EYWANAME=${EYWANAME} >> $HOME/.bash_profile
source ~/.bash_profile
docker stop $EYWANAME
rm -rf /app/.data/leveldb/$EYWANAME/chain-421613
curl -o - -L http://eywatchain-421613.stavr.tech:1002/chain-421613/chain-421613.tar.lz4 | lz4 -c -d - | tar -x -C /app/.data/leveldb/$EYWANAME/ --strip-components 4
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Restart node")
docker restart $(docker ps -a --format='{{json .}}'|jq -r 'select(.Image|match("eywa-p2p-bridge")).Names')

break
;;
"Check node sync")
curl -s 127.0.0.1:8081/v1/sync_state|jq -r '("NODE SYNC STATE: "+.result.state),((["CHAIN","SYNCED","DIFFS","sysDIFFS"] | (., map(length*"-"))),(.result.details|keys[] as $k |["\($k)", "\(.[$k].synced)", "\(.[$k].diffs.processedHeight)", "\(.[$k].diffs.sysProcessedHeight)"])|@tsv)'

break
;;
"Exit")
exit
esac
done
done
